/*
 * generated by Xtext 2.20.0
 */
package epc.text;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class EpcStandaloneSetup extends EpcStandaloneSetupGenerated {

	public static void doSetup() {
		new EpcStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
