/*
 * generated by Xtext 2.20.0
 */
package epc.text.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class EpcUiModule extends AbstractEpcUiModule {

	public EpcUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
